### ISSUE TITLE
get.nutzboot.io下载项目无法启动

### ISSUE THREAD

**Issue by henanxishuashua** [nutzam/nutzboot#131]
```log
日志信息
[ERROR] 16:45:01.882 org.nutz.boot.NbApp.run(NbApp.java:186) - something happen
java.lang.RuntimeException: Context 'app' had been deposed!
	at org.nutz.lang.Lang.makeThrow(Lang.java:134)
	at org.nutz.ioc.impl.ScopeContext.checkBuffer(ScopeContext.java:39)
	at org.nutz.ioc.impl.ScopeContext.fetch(ScopeContext.java:55)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:180)
	at org.nutz.ioc.impl.NutIoc.get(NutIoc.java:271)
	at org.nutz.boot.AppContext.getBeans(AppContext.java:321)
	at org.nutz.boot.AppContext.stopServers(AppContext.java:305)
	at org.nutz.boot.NbApp._shutdown(NbApp.java:225)
	at org.nutz.boot.NbApp.run(NbApp.java:183)
	at com.yqwoe.MainLauncherKt.main(MainLauncher.kt:9)
```

```
import org.nutz.boot.NbApp
import org.nutz.ioc.loader.annotation.IocBean
import org.nutz.mvc.annotation.*;


fun main(args : Array<String>){
    NbApp().run()
}

@IocBean
class MainLauncher{

    @At("/")
    @Ok("->:/index.html")
    fun index(){

    }
}
```
使用的kotlin创建的MainLauncher
这是什么问题呢

**Comment by wendal** [comment]
？？？？？？

**Comment by wendal** [comment]
这是解决了？？原因是啥？？

**Comment by ywjno** [comment]
不懂，没复现
