### ISSUE TITLE
java.lang.NoSuchMethodError: org.nutz.boot.AppContext.getServerPort(Ljava/lang/String;)I

### ISSUE THREAD

**Issue by liubeihb** [nutzam/nutzboot#93]
```
[DEBUG] 22:06:43.622 org.nutz.ioc.impl.NutIoc.get(NutIoc.java:220) - 	 >> Make...'jedisStarter'<class org.nutz.boot.starter.redis.JedisStarter>
[DEBUG] 22:06:43.622 org.nutz.ioc.impl.ScopeContext.save(ScopeContext.java:64) - Save object 'jedisStarter' to [app] 
[DEBUG] 22:06:43.622 org.nutz.ioc.aop.impl.DefaultMirrorFactory.getMirror(DefaultMirrorFactory.java:70) - Load class org.nutz.boot.starter.redis.JedisStarter without AOP
[DEBUG] 22:06:43.625 org.nutz.resource.Scans.scan(Scans.java:280) - Found 1 resource by src( org/nutz/integration/jedis/jedis.js ) , regex( ^(.+[.])(js|json)$ )
[DEBUG] 22:06:43.625 org.nutz.ioc.loader.json.JsonLoader.<init>(JsonLoader.java:49) - loading [org/nutz/integration/jedis/jedis.js]
[DEBUG] 22:06:43.625 org.nutz.ioc.loader.json.JsonLoader.<init>(JsonLoader.java:57) - Loaded 9 bean define from path=[org/nutz/integration/jedis/jedis.js] --> [redisService, jedisCluster, jedisClusterNodes, jedisClusterWrapper, pubSubService, jedisPoolConfig, jedisPool, jedisAgent, redis]
[INFO ] 22:06:43.637 org.eclipse.jetty.util.log.Log.initialized(Log.java:192) - Logging initialized @632ms to org.eclipse.jetty.util.log.Slf4jLog
[ERROR] 22:06:43.709 org.nutz.boot.NbApp._run(NbApp.java:208) - something happen!!
java.lang.NoSuchMethodError: org.nutz.boot.AppContext.getServerPort(Ljava/lang/String;)I
	at org.nutz.boot.starter.jetty.JettyStarter.getPort(JettyStarter.java:227)
	at org.nutz.boot.starter.jetty.JettyStarter.init(JettyStarter.java:126)
	at org.nutz.boot.AppContext.init(AppContext.java:274)
	at org.nutz.boot.NbApp._run(NbApp.java:194)
	at org.nutz.boot.NbApp.run(NbApp.java:170)
	at com.weixin.vote.MainLauncher.main(MainLauncher.java:41)
[DEBUG] 22:06:43.729 org.nutz.ioc.impl.NutIoc.get(NutIoc.java:163) - Get 'jettyStarter'<interface org.nutz.boot.starter.ServerFace>
[INFO ] 22:06:43.731 org.nutz.ioc.impl.NutIoc.depose(NutIoc.java:284) - org.nutz.ioc.impl.NutIoc@4298289 is closing. startup date [18-01-05 22:06:43.500]
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'jedisStarter' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'druidWebStatServletStarter' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'druidWebStatFilterStarter' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'dataSourceStarter' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'nutDaoStarter' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object '$views_velocity' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'whaleFilterStarter' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'nutFilterStarter' ...
[DEBUG] 22:06:43.732 org.nutz.ioc.impl.ScopeContext.clear(ScopeContext.java:108) - Depose object 'jettyStarter' ...
```

**Comment by liubeihb** [comment]
这个something happen  是什么问题啊?

**Comment by wendal** [comment]
等5分钟, 正在重新build, CI的原因

**Comment by wendal** [comment]
https://travis-ci.org/nutzam/nutzboot

**Comment by wendal** [comment]
原因在于build已经成功,然后deploy的时候, 前几个库成功了, 后面失败了, 出现不一致了

**Comment by haoqoo** [comment]
今晚能解决吗？正在和@liubeihb  
写个项目……

**Comment by wendal** [comment]
肯定能的, 放心

**Comment by haoqoo** [comment]
威武

**Comment by wendal** [comment]
mvn -U package吧, 已经build完deploy完成了

**Comment by haoqoo** [comment]
ok

**Comment by wendal** [comment]
ok了的话, 记得回一下话哦

**Comment by haoqoo** [comment]
不行

**Comment by haoqoo** [comment]
睡啦

**Comment by liubeihb** [comment]
老哥. 问题依旧

**Comment by liubeihb** [comment]
@wendal

**Comment by wendal** [comment]
命令行下试过了吗?

**Comment by wendal** [comment]
mvn -U clean package

我刚在服务器测试一下, 没问题的呢

**Comment by liubeihb** [comment]
我刚才试了.  mvn -U package  也看到包的更新了. 还是刚才的问题. 我再来试下mvn -U clean package 命令

**Comment by wendal** [comment]
pom.xml里面的nutzboot-starter依赖删掉

**Comment by haoqoo** [comment]
删除后，可以启动。安心睡觉啦

**Comment by haoqoo** [comment]
能发个固定版本吗？

**Comment by wendal** [comment]
下周就发
